language: clojure
matrix:
  include:
    - jdk: openjdk12
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
notifications:
  slack:
    secure: xiLotownh6HA26oXemm4S25o5Qtgkz/c/GEJD6RZWyEV+nQov1+uB6dyCn8hEeGatrieXDmXk7MCKNsnRfZ5HzOm7H+Qf6ryIt15SeOkVxGjDClU/FGy30Wni9F+7ezQ82H+w2kmb0YfeRk/YBt15/9OBbtl8W3ww1Fg/6Jx0ZzgxOrqKaM6agTN1FnRpZMyaQLDC+lh22NLcLXQH3VseujbBFfinSpw5DsDSX9GbuPnIxCSYVvpZlmtWd3zgFiFIQMrBLZRIkH3VjtoRULXzyImnQspeMGQ1KABuMJpbSOOnQkVa0FRDsnWQmOIZlmpBuIEM8OSFb4xoKVJfKPppia2McX6p71VHSDIkgIzHMEUneKuMb6LJSXpDh7u2YTEivVTOAnPCfDsMScrNLXJGqkfOc1DDN4diK4bhinEZsbE93HkteG86G7z/Rso5BcYgkOxs5nVS6inGgI1ADg53kBngu2NLmt7tRYurqlM7VoN061KenO/FWLVaSAn3O/Kb9xRAI0Q2qRSabt1O7g/iwYiDdMCMld5O7EpIFzLBfLpfUCkFKoRgI57vNGBvTCkILuSPXkfRpeSdOFalw7vagBh+twf3PALzKeQHkRqesH6fJCUgdVBLY9DpuLibK9zEw1XKCAq/VmS1pf9Rylbqdq+CpvO1qawrRTD0gDUVDc=
